#!/usr/bin/env node
/**
 * Copies the licensed sources in /assets into the web app's public folder.
 * /assets is the source of truth; apps/web/public/{logo,media} are build output and gitignored.
 * Nothing is ever fetched from a URL here — see docs/design-reference.md, "Media rules".
 */
import { cp, mkdir, readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const publicDir = join(root, 'apps', 'web', 'public');

/**
 * The still plates ship with the repo — they are original artwork generated by
 * scripts/generate-hero-art.mjs, so a missing one means someone deleted it rather than that the
 * client still owes us a file. Run `npm run art:generate` to put them back.
 */
const EXPECTED_MEDIA = [
  'hero-home.svg',
  'hero-about.svg',
  'hero-platform.svg',
  'hero-datanerve.svg',
  'hero-ainerve.svg',
  'hero-contact.svg',
];

/**
 * Licensed photography. Unlike the plates above these are third-party files, so a missing one means
 * it was never downloaded rather than that a generator needs re-running — but the failure mode is
 * the same either way, because every consumer checks AVAILABLE_MEDIA before rendering. Each has a
 * row in docs/licences.csv; no row, no ship.
 */
const EXPECTED_PHOTOS = [
  'hero-home-poster.jpg',
  'img-platform.jpg',
  'img-datanerve.jpg',
  'img-ainerve.jpg',
  'img-socmint.jpg',
  'img-integrations.jpg',
  'img-infrastructure.jpg',
  'img-audit.jpg',
  'img-services-data.jpg',
  'img-services-ai.jpg',
  'img-about.jpg',
  'img-partners.jpg',
  'img-governance.jpg',
  'img-dspm.jpg',
  'img-dlp.jpg',
  'img-article-1.jpg',
  'img-article-2.jpg',
  'img-article-3.jpg',
];

/**
 * Optional footage. The heroes run on the still plate plus the animated canvas without these; drop
 * a licensed clip in with one of these names and that hero starts using it instead. Absence is the
 * expected state, so it is reported separately and never as a warning.
 */
const OPTIONAL_MEDIA = [
  'hero-home.mp4',
  'hero-home.webm',
  'hero-about.mp4',
  'hero-about.webm',
];

const syncDir = async (name) => {
  const from = join(root, 'assets', name);
  const to = join(publicDir, name);
  await mkdir(to, { recursive: true });
  if (!existsSync(from)) return [];
  await cp(from, to, { recursive: true, filter: (src) => !src.endsWith('README.md') });
  return (await readdir(from)).filter((file) => file !== 'README.md');
};

const logo = await syncDir('logo');
const media = await syncDir('media');

const missing = [...EXPECTED_MEDIA, ...EXPECTED_PHOTOS].filter((file) => !media.includes(file));

/**
 * The web app needs to know which hero files actually exist, so a missing one falls back to the
 * authored generative backdrop instead of rendering a broken <video>. Drop a real file into
 * assets/media and the next build picks it up with no code change.
 */
await writeFile(
  join(root, 'apps', 'web', 'src', 'generated', 'media.ts'),
  `/* Generated by scripts/sync-assets.mjs. Do not edit — run \`npm run assets:sync\`. */\n` +
    `export const AVAILABLE_MEDIA: readonly string[] = ${JSON.stringify(
      media.map((file) => `/media/${file}`).sort(),
      null,
      2,
    )};\n`,
);

const footage = OPTIONAL_MEDIA.filter((file) => media.includes(file));

console.log(`assets: ${logo.length} logo file(s), ${media.length} media file(s) synced`);
console.log(
  `assets: ${footage.length} of ${OPTIONAL_MEDIA.length} optional video files present` +
    (footage.length === 0 ? ' — heroes run on the still plates plus the animated canvas' : ''),
);

if (missing.length > 0) {
  console.warn(
    `assets: ${missing.length} of ${EXPECTED_MEDIA.length + EXPECTED_PHOTOS.length} expected files missing — those slots fall back to the canvas alone.\n` +
      `         ${missing.join(', ')}\n` +
      `         Run \`npm run art:generate\` to regenerate them.`,
  );
}
